//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaleManager.WebApi.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Discount
    {
        public int Id { get; set; }
        public byte Type { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public Nullable<System.DateTime> CreateAt { get; set; }
        public string CreateBy { get; set; }
        public string Barcode { get; set; }
    }
}
