//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaleManager.WebApi.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public int Id { get; set; }
        public Nullable<byte> Type { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public Nullable<int> SuplierId { get; set; }
        public Nullable<byte> IsPayment { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<decimal> Payment { get; set; }
        public Nullable<decimal> PayBack { get; set; }
        public Nullable<int> BillNumber { get; set; }
        public Nullable<System.DateTime> CreateAt { get; set; }
        public string CreateBy { get; set; }
    }
}
